server:
  port: 9998
spring:
  application:
    name: sc-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
ribbon.eureka.enabled: false

zuul:
  routes:
    myapi:
      path: /myapi/**
      url: http://localhost:9997